### ISSUE TITLE
Wrong images references in docker-compose.yml

### ISSUE THREAD

**Issue by thorify** [agustingenoud/spark-delta_lake-jupyterlab#1]
You should have put:
```
build:
    context:
```

instead of `image:`

Then the `docker-compose.yml` should look:

```
version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: "local"

services:
  jupyterlab:
    build: 
      context: ./00-build-images/04-jupyterlab
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - shared-workspace:/opt/workspace
      - ./jupyter-folder:/opt/workspace/jupyter-folder
      - ./data:/opt/workspace/data

  spark-master:
    build:
      context: ./00-build-images/02-spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    build: 
      context: ./00-build-images/03-spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - "8081:8081"
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    build:
      context: ./00-build-images/03-spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - "8082:8081"
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
```
